### ISSUE TITLE
Correction insister takes focus away from textbox, causes accidental back navigation

### ISSUE THREAD

**Issue by melarish** [eedrah/duolingo-scripts#1]
When you use the correction insister script, it brings your focus away from the textbox when you fix your answer. So when you accidentally press backspace too many times (to delete an unnecessary word), you'll navigate back in the browser, losing your progress in the practice.

Expected behaviour: focus stays in textbox even when you have fixed your answer.

**Comment by eedrah** [comment]
Thanks for logging the issue. What browser are you currently using? I thought most of the major browsers fixed the "Backspace navigates backwards" issue sometime ago. For example, in Chrome, backspace does nothing.

Unfortunately I'm currently travelling the world (Thanks Duolingo ;) ) and will not have access to a computer for some time. If someone makes a pull request I could accept the fix, otherwise it will have to wait for when I settle down for a bit.

**Comment by melarish** [comment]
Ha, yes they changed backspace to do nothing but many people considered it a good feature, not an issue, so there's scripts (Backspace to Go Back) to bring it back. According to Chrome extension store, this script has 82,646 users (how many of those use your script too? possibly no one) so up to you if you consider it important enough :)

I think I can fix it for myself if I comment out this._deactivate() line in monitorCorrectAnswer (possibleAnswers, continueButton)?

**Comment by eedrah** [comment]
Ok, it's great you can fix it, and it's good to have it logged here so others can see. I think it's the appropriate thing to focus on supporting the core browser behaviour, which means not adding to the code base for supporting another script which - as advertised in the title - clashes with the behaviour.

(That being said, I'd consider it the responsibility of the script "Backspace to Go Back" to monitor and not clash with other scripts' event handlers - I'm almost certainly not the only script that this clashes with.)
