### ISSUE TITLE
Duolingo Correction Insistor not working in Pale Moon in Ubuntu

### ISSUE THREAD

**Issue by graciecat** [eedrah/duolingo-scripts#3]
Duolingo Correction Insistor does not appear to work in Pale Moon 27 in Ubuntu 14.04.  It's as though the script were not installed. Other Duolingo scripts work.

Ubuntu 14.0.5
[Pale Moon 27.2.0 (64-bit)](url=http://www.palemoon.org/) 
[Greasemonkey 3.9.2 (fork)](url=https://github.com/janekptacijarabaci/greasemonkey/releases/tag/3.9.2Fork)

@janekptacijarabaci  I am not sure if the problem lies with the script or with the Greasemonkey fork.

**Comment by janekptacijarabaci** [comment]
Pale Moon does not support `classes`.

**Comment by graciecat** [comment]
So this cannot be fixed? :(

**Comment by eedrah** [comment]
At a guess, is this due to the missing es6 support? I had a skim over this ( https://www.palemoon.org/roadmap.shtml ) and they might implement it slowly.

Unfortunately I'm currently travelling the world (Thanks Duolingo ;) ) and will not have access to a computer for some time. If someone makes a pull request I could accept the fix, otherwise it will have to wait for when I settle down for a bit.

**Comment by eedrah** [comment]
Looks like there are bigger things at hand with the other issue, so I'll close this for now - let me know if you want it reopened.
